ljmu:
    microserviceA:
        url: http://localhost:8001/serviceA

spring:
    application:
        name: microservice-B
        version: 1.0.0
    datasource:
        url: jdbc:postgresql://localhost:5433/ljmu_upgrad
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
    port: 8002
    servlet:
        context-path: /serviceB

management.endpoints.web.exposure.include: metrics